"""add priority field to task table

Revision ID: 4fb90ad39f9a
Revises: b6ec7428b7d4
Create Date: 2026-01-26 23:06:05.472412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fb90ad39f9a'
down_revision: Union[str, Sequence[str], None] = 'b6ec7428b7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
